import { LessonPlanProject } from '@/types/lesson-plan';

export const INITIAL_LESSON_PLAN: LessonPlanProject = {
  id: '550e8400-e29b-41d4-a716-446655440000',
  subject: 'Tin học & Công nghệ số',
  gradeLevel: 'Lớp 10',
  lessonName: 'Trí tuệ nhân tạo và Ứng dụng trong Đời sống',
  durationPeriod: 45,
  updatedAt: new Date().toISOString(),
  objectives: [
    {
      id: 'd9b2d621-7299-4d6c-bb9e-2f95b058a001',
      category: 'KNOWLEDGE',
      description: 'Trình bày được định nghĩa cơ bản về AI và phân biệt được AI hẹp với AGI.',
      bloomLevel: 'UNDERSTAND',
    },
    {
      id: 'd9b2d621-7299-4d6c-bb9e-2f95b058a002',
      category: 'SKILL',
      description: 'Phân tích các ca ứng dụng thực tiễn của AI trong y tế, giao thông và giáo dục.',
      bloomLevel: 'ANALYZE',
    },
    {
      id: 'd9b2d621-7299-4d6c-bb9e-2f95b058a003',
      category: 'ATTITUDE',
      description: 'Ý thức trách nhiệm đạo đức và bảo mật dữ liệu cá nhân khi sử dụng công cụ AI.',
      bloomLevel: 'EVALUATE',
    },
  ],
  activities: [
    {
      id: 'a1111111-1111-4111-8111-111111111111',
      phase: 'WARM_UP',
      title: 'Trò chơi Thử thách Turing Mini: Người hay Máy?',
      durationMinutes: 7,
      teacherRole: 'Trình chiếu 3 bức tranh và 2 đoạn văn bản, đặt câu hỏi phân biệt sáng tạo AI.',
      studentRole: 'Tham gia dự đoán qua biểu quyết thẻ màu, giải thích lý do nhận diện.',
      expectedProduct: 'Bảng tổng hợp dự đoán của 4 tổ và sự tò mò kích hoạt bài học.',
    },
    {
      id: 'a2222222-2222-4222-8222-222222222222',
      phase: 'KNOWLEDGE',
      title: 'Khám phá Bản chất Trí tuệ Nhân tạo & Thuật toán Học máy',
      durationMinutes: 18,
      teacherRole: 'Dẫn dắt phân tích sơ đồ luồng dữ liệu học máy (Input -> Model -> Output).',
      studentRole: 'Thảo luận nhóm đôi, hoàn thành phiếu học tập số 1 về 3 trụ cột AI.',
      expectedProduct: 'Phiếu học tập cá nhân đã hoàn thiện sơ đồ khái niệm AI.',
    },
    {
      id: 'a3333333-3333-4333-8333-333333333333',
      phase: 'PRACTICE',
      title: 'Phân tích Tình huống Ứng dụng AI Thực tiễn',
      durationMinutes: 13,
      teacherRole: 'Giao 4 trạm nghiên cứu: Y học, Xe tự hành, Dịch thuật, Thị giác máy tính.',
      studentRole: 'Các nhóm luân chuyển trạm, phân tích lợi ích và thách thức đạo đức.',
      expectedProduct: 'Infographic mini trên giấy A3 tóm tắt ca ứng dụng của mỗi nhóm.',
    },
    {
      id: 'a4444444-4444-4444-8444-444444444444',
      phase: 'APPLICATION',
      title: 'Đề xuất Ý tưởng Giải pháp AI vì Cộng đồng',
      durationMinutes: 7,
      teacherRole: 'Đưa ra thử thách "AI xanh cho trường học", gợi ý tiêu chí đánh giá.',
      studentRole: 'Đề xuất 1 ý tưởng ứng dụng AI giải quyết vấn đề rác thải hoặc tiết kiệm điện.',
      expectedProduct: 'Flashcard ý tưởng sáng tạo nộp lại cuối giờ học.',
    },
  ],
  slides: [
    {
      id: 's1111111-1111-4111-8111-111111111111',
      slideNumber: 1,
      layout: 'TITLE_HERO',
      title: 'TRÍ TUỆ NHÂN TẠO & ĐỜI SỐNG SỐ',
      bullets: [
        'Khai phá kỷ nguyên công nghệ thông minh 2026',
        'Phát triển tư duy công nghệ và kỹ năng số',
        'Bộ môn Tin học - Khối 10',
      ],
      teacherScript: 'Chào cả lớp, hôm nay chúng ta cùng bước vào thế giới kỳ thú của Trí tuệ Nhân tạo.',
      visualSuggestion: 'Hình nền tối sang trọng với các đường mạch nơ-ron phát sáng ánh xanh cyan.',
    },
    {
      id: 's2222222-2222-4222-8222-222222222222',
      slideNumber: 2,
      layout: 'INTERACTIVE_QUIZ',
      title: 'Khởi động: Thử thách Turing Mini',
      bullets: [
        'Bức họa A vs B: Bức tranh nào do AI tạo ra?',
        'Quan sát độ chi tiết ánh sáng và nét vẽ',
        'Biểu quyết nhanh bằng thẻ phản hồi',
      ],
      teacherScript: 'Hãy giơ thẻ màu xanh nếu chọn tranh A và thẻ đỏ nếu chọn tranh B. Ai có thể giải thích?',
      visualSuggestion: 'Chia đôi màn hình so sánh tranh con người vẽ và tác phẩm Midjourney/DALL-E.',
    },
    {
      id: 's3333333-3333-4333-8333-333333333333',
      slideNumber: 3,
      layout: 'CONCEPT_BREAKDOWN',
      title: 'Hình thành kiến thức: 3 Trụ Cột Của AI Hiện Đại',
      bullets: [
        'Dữ liệu lớn (Big Data): Nguồn thức ăn cho mô hình',
        'Thuật toán học máy (Machine Learning): Bộ não suy luận',
        'Năng lực tính toán (Compute): Sức mạnh tăng tốc xử lý',
      ],
      teacherScript: 'Các em chú ý, AI không phải phép màu, nó được nuôi dưỡng bởi 3 thành tố cốt lõi này.',
      visualSuggestion: '3 khối module đồ họa 3D xếp chồng tạo thành cấu trúc vững chãi.',
    },
    {
      id: 's4444444-4444-4444-8444-444444444444',
      slideNumber: 4,
      layout: 'COMPARISON_TABLE',
      title: 'Luyện tập: So Sánh Trí Tuệ Tự Nhiên & AI',
      bullets: [
        'Tốc độ xử lý: Con người hạn chế - AI vượt bậc',
        'Cảm xúc & Trực giác: Con người phong phú - AI bằng 0',
        'Khả năng khái quát: Con người linh hoạt - AI theo dữ liệu',
      ],
      teacherScript: 'Mời đại diện nhóm 2 và nhóm 3 đưa ra phản biện về khả năng thấu cảm của máy móc.',
      visualSuggestion: 'Bảng đối chiếu 2 cột màu gradient tương phản cam và xanh lam.',
    },
    {
      id: 's5555555-5555-4555-8555-555555555555',
      slideNumber: 5,
      layout: 'SUMMARY_MINDMAP',
      title: 'Vận dụng: Thông Điệp Đạo Đức & Kỷ Nguyên Số',
      bullets: [
        'Sử dụng AI có trách nhiệm và liêm chính học thuật',
        'Bảo vệ dữ liệu cá nhân trên môi trường mạng',
        'Nhiệm vụ về nhà: Xây dựng dự án AI Xanh',
      ],
      teacherScript: 'Hãy luôn nhớ: Công nghệ là công cụ, trí tuệ và đạo đức con người mới là kim chỉ nam.',
      visualSuggestion: 'Sơ đồ tư duy mở rộng từ trung tâm ra các nhánh hành động thực tiễn.',
    },
  ],
};
