import { SlideTheme } from '@/types/template';

export const BUILTIN_THEMES: SlideTheme[] = [
  {
    id: 'TECH_DARK',
    name: 'Hiện Đại Công Nghệ',
    description: 'Tone tối sang trọng, điểm nhấn ánh sáng cyan/amber',
    bgHeroHex: '0F172A',
    bgSlideHex: '0F172A',
    accentHex: '0284C7',
    textHeroHex: 'F8FAFC',
    textSlideHex: 'F8FAFC',
    badgeBg: 'bg-slate-900',
    badgeText: 'text-cyan-400',
    previewGradient: 'from-slate-900 via-indigo-950 to-slate-900',
    unifiedBgClass: 'bg-slate-950 text-white',
    unifiedCardClass: 'bg-slate-900/90 border border-slate-800 text-slate-100 shadow-sm',
    unifiedTitleClass: 'text-white font-extrabold',
    unifiedTextClass: 'text-slate-300',
  },
  {
    id: 'PEDAGOGY_BLUE',
    name: 'Sư Phạm Chuẩn Mực',
    description: 'Tone xanh dương thanh lịch, trang nhã chuẩn mực giáo dục',
    bgHeroHex: '1E3A8A',
    bgSlideHex: '1E3A8A',
    accentHex: '38BDF8',
    textHeroHex: 'FFFFFF',
    textSlideHex: 'FFFFFF',
    badgeBg: 'bg-blue-950',
    badgeText: 'text-blue-200',
    previewGradient: 'from-blue-900 via-indigo-900 to-blue-950',
    unifiedBgClass: 'bg-blue-950 text-white',
    unifiedCardClass: 'bg-blue-900/80 border border-blue-800 text-white shadow-sm',
    unifiedTitleClass: 'text-white font-extrabold',
    unifiedTextClass: 'text-blue-100',
  },
  {
    id: 'ECO_GREEN',
    name: 'Sinh Thái & Tự Nhiên',
    description: 'Tone xanh lục dịu mát, phù hợp Sinh - Địa - KHTN',
    bgHeroHex: '064E3B',
    bgSlideHex: '064E3B',
    accentHex: '34D399',
    textHeroHex: 'FFFFFF',
    textSlideHex: 'FFFFFF',
    badgeBg: 'bg-emerald-950',
    badgeText: 'text-emerald-200',
    previewGradient: 'from-emerald-900 via-teal-900 to-emerald-950',
    unifiedBgClass: 'bg-emerald-950 text-white',
    unifiedCardClass: 'bg-emerald-900/80 border border-emerald-800 text-emerald-50 shadow-sm',
    unifiedTitleClass: 'text-white font-extrabold',
    unifiedTextClass: 'text-emerald-100',
  },
  {
    id: 'WARM_AMBER',
    name: 'Nhân Văn & Lịch Sử',
    description: 'Tone vàng hổ phách trầm ấm, phù hợp Văn - Sử - GDCD',
    bgHeroHex: '451A03',
    bgSlideHex: '451A03',
    accentHex: 'FBBF24',
    textHeroHex: 'FFFFFF',
    textSlideHex: 'FFFFFF',
    badgeBg: 'bg-amber-950',
    badgeText: 'text-amber-200',
    previewGradient: 'from-amber-950 via-yellow-950 to-stone-900',
    unifiedBgClass: 'bg-stone-950 text-white',
    unifiedCardClass: 'bg-amber-950/80 border border-amber-900 text-amber-50 shadow-sm',
    unifiedTitleClass: 'text-white font-extrabold',
    unifiedTextClass: 'text-amber-100',
  },
  {
    id: 'MINIMAL_SLATE',
    name: 'Tối Giản Tinh Tế',
    description: 'Phong cách tối giản hiện đại, rõ ràng, tập trung nội dung',
    bgHeroHex: '1E293B',
    bgSlideHex: '1E293B',
    accentHex: '38BDF8',
    textHeroHex: 'FFFFFF',
    textSlideHex: 'FFFFFF',
    badgeBg: 'bg-slate-900',
    badgeText: 'text-slate-300',
    previewGradient: 'from-slate-900 via-slate-800 to-zinc-900',
    unifiedBgClass: 'bg-slate-900 text-white',
    unifiedCardClass: 'bg-slate-800/90 border border-slate-700 text-slate-100 shadow-sm',
    unifiedTitleClass: 'text-white font-extrabold',
    unifiedTextClass: 'text-slate-200',
  },
];

export function getThemeById(themeId?: string): SlideTheme {
  return BUILTIN_THEMES.find((t) => t.id === themeId) ?? BUILTIN_THEMES[0];
}
